website/models.py
from . import db
from flask_login import UserMixin


class City(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(150), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    cities = db.relationship('City')

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager


db = SQLAlchemy()
DB_NAME = "WeatherAPP.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'thesecretkey'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, City

    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Database Created!')

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home_get'))
            else:
                flash('Incorrect password, try again', category='error')
        else:
            flash('Email does not exists.', category='error')


    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('User alerady exists!', category='error')
        elif len(email) < 4:
            flash("Email must be greater than 4 caracters.", category='error')
        elif len(first_name) < 2:
            flash("First Name must be greater than 1 caracter.", category='error')
        elif password1 != password2:
            flash("Your passwords don't match.", category='error')
        elif len(password1) < 7:
            flash("Password must be at least 7 caracters.", category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash("Account created", category='success')
            return  redirect(url_for('views.home_get'))

    return render_template("sign_up.html", user=current_user)

website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import City
from flask_login import login_required, current_user
from . import db
import requests

views = Blueprint('views', __name__)


def get_weather_data(city):
    api_url = f'https://api.openweathermap.org/data/2.5/weather?q={city}&units=metric&appid=0e6cb33cd24973e9f6a48b2f6ad67a93'
    r = requests.get(api_url).json()
    return r

@views.route('/')
@login_required
def home_get():

    cities = City.query.filter_by(user_id=current_user.id).all()

    weather_data = []

    for city in cities:
        r = get_weather_data(city.name)

        weather = {
            'city': city.name,
            'temperature': r['main']['temp'],
            'description': r['weather'][0]['description'],
            'icon': r['weather'][0]['icon'],
        }
        weather_data.append(weather)

    return render_template('home.html', user=current_user, weather_data=weather_data)


@views.route('/', methods=['POST'])
@login_required
def home_post():
    new_city = request.form.get('city')

    if new_city:
        existing_city = City.query.filter(City.name.like(new_city),  City.user_id.like(current_user.id)).first()
        if not existing_city:
            check_city = get_weather_data(new_city)
            if check_city['cod'] == 200:
                new_city_obj = City(name=new_city, user_id=current_user.id)
                db.session.add(new_city_obj)
                db.session.commit()
            else:
                flash('City does not exists!', category='error')
        else:
            flash('The city already exists!', category='error')
    flash('Successfully added the city!', 'success')
    return redirect(url_for('views.home_get'))


@views.route('/delete/<name>')
@login_required
def delete_city(name):

    city = City.query.filter(City.name.like(name),  City.user_id.like(current_user.id)).first()
    db.session.delete(city)
    db.session.commit()

    flash(f'Successfully deleted {city.name}', 'success')
    return redirect(url_for('views.home_get'))

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" />
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous"
        />
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          crossorigin="anonymous"
        />
        <style>
            body::-webkit-scrollbar {
                display: none;
            }
        </style>

        <title>{% block title %}Home{% endblock %}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbar"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" id="home" href="/">Home</a>
                    <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" id="login" href="/login">Login</a>
                    <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
                {% endif %}
            </div>
          </div>
        </nav>

        <div>
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        {% if category == 'error' %}
                            <div class="alert alert-danger alert-dismissable fade show" role="alert">
                                {{ message }}
                                <button type="button" class="close" data-dismiss="alert">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% else %}
                            <div class="alert alert-success alert-dismissable fade show" role="alert">
                                {{ message }}
                                <button type="button" class="close" data-dismiss="alert">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            {% endwith %}
        </div>

        <div class="container">
            {% block content %}
            {% endblock %}
        </div>

        <script
          src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
          integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
          crossorigin="anonymous"
        ></script>
        <script
          src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
          integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
          crossorigin="anonymous"
        ></script>
        <script
          src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
          integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
          crossorigin="anonymous"
        ></script>

        <script
            type="text/javascript"
            src="{{ url_for('static', filename='index.js')}}"
        ></script>
    </body>
</html>

website/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<section class="hero is-primary">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    What's the weather like?
                </h1>
            </div>
        </div>
    </section>
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
                    <form method="POST">
                        <div class="field has-addons">
                            <div class="control is-expanded">
                                <input class="input" name="city" type="text" placeholder="City Name">
                            </div>
                            <div class="control">
                                <button class="button is-info">
                                    Add City
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
                    {% for weather in weather_data %}
                    <div class="box">
                        <article class="media">
                            <div class="media-left">
                                <figure class="image is-50x50">
                                    <img src="http://openweathermap.org/img/w/{{ weather.icon }}.png" alt="Image">
                                </figure>
                            </div>
                            <div class="media-content">
                                <div class="content">
                                    <p>
                                        <span class="title">{{ weather.city }}</span>
                                        <br>
                                        <span class="subtitle">{{ weather.temperature }} C°</span>
                                        <br> {{ weather.description }}
                                    </p>
                                </div>
                            </div>

                            <div class="media-right">
                                <a href="{{ url_for('views.delete_city', name=weather.city) }}">
                                    <button class="delete"></button>
                                </a>
                            </div>

                        </article>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
    <div style="margin-top: 2%!important;" class="row justify-content-md-center">
        <div class="col-lg-4">
            <div class="card">
                <div class="card-header">
                    <h5>Login</h5>
                </div>
                <div class="card-body">
                    <form method="POST">
                        <div class="form-group">
                            <label for="email">Email Address:</label>
                            <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
                        </div>
                        <div class="form-group">
                            <label for="password">Password:</label>
                            <input type="password" class="form-control" id="password" name="password" placeholder="Enter password">
                        </div>
                        </br>

                        <button type="submit" class="btn btn-primary">Login</button>

                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %}

{% block title %}Sign Up{% endblock %}

{% block content %}
    <div style="margin-top: 2%!important;" class="row justify-content-md-center">
        <div class="col-lg-4">
            <div class="card">
                <div class="card-header">
                    <h5>Sign Up</h5>
                </div>
                <div class="card-body">
                    <form method="POST">

                        <div class="form-group">
                            <label for="email">Email Address:</label>
                            <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
                        </div>
                        <div class="form-group">
                            <label for="firstName">Email Name:</label>
                            <input type="text" class="form-control" id="firstName" name="firstName" placeholder="Enter name">
                        </div>
                        <div class="form-group">
                            <label for="password1">Password:</label>
                            <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter password">
                        </div>
                        <div class="form-group">
                            <label for="password2">Password (Confirm):</label>
                            <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirm password">
                        </div>
                        </br>
                        <button type="submit" class="btn btn-primary">Submit</button>

                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}